/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

/**
 *
 * @author elimo
 */
public class FrmHomeTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form FrmHomeTrabajador
     */
    public FrmHomeTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMantenimiento = new javax.swing.JLabel();
        lblMantenimiento1 = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        lblRegistrar1 = new javax.swing.JLabel();
        lblQuejas = new javax.swing.JLabel();
        lblQuejas1 = new javax.swing.JLabel();
        lblTickets = new javax.swing.JLabel();
        lblTickets1 = new javax.swing.JLabel();
        lblSesion = new javax.swing.JLabel();
        lblSesion1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMantenimiento.setText("mantenimiento");
        jPanel1.add(lblMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 180, 50));

        lblMantenimiento1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMantenimiento1.setText("Programar ");
        jPanel1.add(lblMantenimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 120, 50));

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrar.setText("empleado");
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 130, 70));

        lblRegistrar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrar1.setText("Registrar");
        jPanel1.add(lblRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 120, 70));

        lblQuejas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuejas.setText("Ver");
        jPanel1.add(lblQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 90, 60));

        lblQuejas1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuejas1.setText("quejas");
        jPanel1.add(lblQuejas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 90, 70));

        lblTickets.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTickets.setText("Atender");
        jPanel1.add(lblTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, 70));

        lblTickets1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTickets1.setText("tickets");
        jPanel1.add(lblTickets1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 90, 70));

        lblSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSesion.setText("Sesión");
        jPanel1.add(lblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 90, 70));

        lblSesion1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSesion1.setText("Cerrar");
        jPanel1.add(lblSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 90, 70));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 6 (2).png"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1120, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHomeTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHomeTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHomeTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHomeTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHomeTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblMantenimiento1;
    private javax.swing.JLabel lblQuejas;
    private javax.swing.JLabel lblQuejas1;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistrar1;
    private javax.swing.JLabel lblSesion;
    private javax.swing.JLabel lblSesion1;
    private javax.swing.JLabel lblTickets;
    private javax.swing.JLabel lblTickets1;
    // End of variables declaration//GEN-END:variables
}
