/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import dtos.UsuarioDTO;
import excepciones.PresentacionException;
import excepciones.RegistrarEmpleadoException;
import java.awt.Color;
import javax.swing.JOptionPane;
import registrarEmpleado.FacadeRegistrarEmpleado;
import registrarEmpleado.IRegistrarEmpleado;
import utilidades.Validador;

/**
 *
 * @author franc
 */
public class FrmRegistrarEmpleado extends javax.swing.JFrame {
    private final IRegistrarEmpleado facadeRegistrarEmpleado;
    /**
     * Creates new form FrmRegistrarEmpleado
     */
    public FrmRegistrarEmpleado() {
        initComponents();
        this.facadeRegistrarEmpleado = new FacadeRegistrarEmpleado();
    }

    private void crearCuentaEmpleado() {
        // Cachamos los atributos ingresados en el formulario.
        String nombres = txtNombres.getText().trim();
        String apellidoP = txtApellidoP.getText().trim();
        String apellidoM = txtApellidoM.getText().trim();
        String telefono = txtTel.getText().trim();
        String curp = txtCurp.getText().trim();
        String rfc = txtRfc.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasenia1 = new String(pwdContrasenia.getPassword()).trim();
        String contrasenia2 = new String(pwdConfirmarContrasenia.getPassword()).trim();
        String tipo = (String) jComboBox1.getSelectedItem();
        // Obtener el índice del elemento seleccionado en el JComboBox
        int opcion = jComboBox1.getSelectedIndex();

        // Actualizar el atributo Tipo dependiendo del elemento seleccionado
        switch (opcion) {
            case 0:
                tipo = "RRHH";
                break;
            case 1:
                tipo = "AACC";
                break;
            case 2:
                tipo = "PPMM";
                break;
        }
        
        // Creamos una instancia del validador.
        Validador validador = new Validador();
        try {
            // Validamos cada dato.
            validador.validarNombres(nombres);
            validador.validarApellidoP(apellidoP);
            validador.validarApellidoM(apellidoM);
            validador.validarTelefono(telefono);
            validador.validarCURP(curp);
            validador.validarRFC(rfc);
            validador.validarCorreo(correo);
            validador.validarContrasenia(contrasenia1);
            validador.validarConfirmarContrasenia(contrasenia1, contrasenia2);
            
            
            // Creamos un usuario DTO con los datos introducidos.
            UsuarioDTO usuario = new UsuarioDTO("",nombres, apellidoP, apellidoM, telefono, curp, rfc, correo, contrasenia1, tipo);

            // Mandamos a crear la cuenta del usuario.
            usuario = facadeRegistrarEmpleado.crearCuenta(usuario);

            // Redireccionamos al usuario al home de trabajador.
            FrmHomeTrabajador frmHome = new FrmHomeTrabajador(usuario);
            frmHome.setVisible(true);
            this.dispose();
            // Mensaje para indicar que el registro se completo correctamente.
            JOptionPane.showMessageDialog(this, "¡Empleado registrado con éxito!", "¡Yippee!", JOptionPane.INFORMATION_MESSAGE);
        } catch (PresentacionException | RegistrarEmpleadoException ex) {
            // Si se obtiene alguna excepción, imprimimos su mensaje.
            JOptionPane.showMessageDialog(this, ex.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        pwdContrasenia = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pwdConfirmarContrasenia = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnRegistrarEmpleado = new javax.swing.JButton();
        lblMantenimiento = new javax.swing.JLabel();
        lblMantenimiento1 = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        lblRegistrar1 = new javax.swing.JLabel();
        lblQuejas = new javax.swing.JLabel();
        lblQuejas1 = new javax.swing.JLabel();
        lblTickets = new javax.swing.JLabel();
        lblTickets1 = new javax.swing.JLabel();
        lblSesion = new javax.swing.JLabel();
        lblSesion1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 270, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Apellido P");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 30));

        txtApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 270, 40));

        txtApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 270, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Apellido M");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, 20));

        txtTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 270, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("CURP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, 30));

        txtCurp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpActionPerformed(evt);
            }
        });
        jPanel1.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 270, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("RFC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, 20));

        txtRfc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        jPanel1.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 270, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, 20));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 270, 40));

        pwdContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(pwdContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 270, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Confirmar contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 200, 20));

        pwdConfirmarContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(pwdConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 270, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 102, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RRHH", "AACC", "PPMM" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, -1, -1));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEmpleado.setText("CREAR");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 130, 50));

        lblMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMantenimiento.setText("mantenimiento");
        lblMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseExited(evt);
            }
        });
        jPanel1.add(lblMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 180, 50));

        lblMantenimiento1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMantenimiento1.setText("Programar ");
        lblMantenimiento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMantenimiento1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMantenimiento1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMantenimiento1MouseExited(evt);
            }
        });
        jPanel1.add(lblMantenimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 120, 50));

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrar.setText("empleado");
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseExited(evt);
            }
        });
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 130, 70));

        lblRegistrar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrar1.setText("Registrar");
        lblRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseExited(evt);
            }
        });
        jPanel1.add(lblRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 120, 70));

        lblQuejas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuejas.setText("Ver");
        lblQuejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuejasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuejasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuejasMouseExited(evt);
            }
        });
        jPanel1.add(lblQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 90, 60));

        lblQuejas1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuejas1.setText("quejas");
        lblQuejas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuejas1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuejas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuejas1MouseExited(evt);
            }
        });
        jPanel1.add(lblQuejas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 90, 70));

        lblTickets.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTickets.setText("Atender");
        lblTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTicketsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTicketsMouseExited(evt);
            }
        });
        jPanel1.add(lblTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, 70));

        lblTickets1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTickets1.setText("tickets");
        jPanel1.add(lblTickets1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 90, 70));

        lblSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSesion.setText("Sesión");
        lblSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSesionMouseExited(evt);
            }
        });
        jPanel1.add(lblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 90, 70));

        lblSesion1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSesion1.setText("Cerrar");
        lblSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSesion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSesion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSesion1MouseExited(evt);
            }
        });
        jPanel1.add(lblSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 90, 70));

        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRegistrarEmpleado (1).png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

   

    

    private void lblRegistrar1Entered(java.awt.event.MouseEvent evt) {
        lblRegistrar1.setForeground(Color.GRAY);
        lblRegistrar.setForeground(Color.GRAY);
    }
    
    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpActionPerformed

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
        crearCuentaEmpleado();
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void lblRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseClicked
        // TODO add your handling code here:
        FrmRegistrarEmpleado frmRegistrar = new FrmRegistrarEmpleado(); // Se muestra un mensaje si no se validó la sesión.
        frmRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistrar1MouseClicked

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        FrmRegistrarEmpleado frmRegistrar = new FrmRegistrarEmpleado(); // Se muestra un mensaje si no se validó la sesión.
        frmRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
        // TODO add your handling code here:
        lblRegistrar.setForeground(Color.GRAY);
        lblRegistrar1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseExited
        // TODO add your handling code here:
        lblRegistrar.setForeground(Color.BLACK);
        lblRegistrar1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRegistrarMouseExited

    private void lblRegistrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseEntered
        // TODO add your handling code here:
        lblRegistrar.setForeground(Color.GRAY);
        lblRegistrar1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblRegistrar1MouseEntered

    private void lblRegistrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseExited
        // TODO add your handling code here:
        lblRegistrar.setForeground(Color.BLACK);
        lblRegistrar1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRegistrar1MouseExited

    private void lblMantenimiento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimiento1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMantenimiento1MouseClicked

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        FrmHomeTrabajador frmRegistrar = new FrmHomeTrabajador(); // Se muestra un mensaje si no se validó la sesión.
        frmRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMantenimientoMouseClicked

    private void lblMantenimiento1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimiento1MouseEntered
        // TODO add your handling code here:
        lblMantenimiento.setForeground(Color.GRAY);
        lblMantenimiento1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblMantenimiento1MouseEntered

    private void lblMantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseEntered
        // TODO add your handling code here:
        lblMantenimiento.setForeground(Color.GRAY);
        lblMantenimiento1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblMantenimientoMouseEntered

    private void lblMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseExited
        // TODO add your handling code here:
        lblMantenimiento.setForeground(Color.BLACK);
        lblMantenimiento1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMantenimientoMouseExited

    private void lblMantenimiento1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimiento1MouseExited
        // TODO add your handling code here:
        lblMantenimiento.setForeground(Color.BLACK);
        lblMantenimiento1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMantenimiento1MouseExited

    private void lblQuejasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuejasMouseClicked

    private void lblQuejasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseEntered
        // TODO add your handling code here:
        lblQuejas.setForeground(Color.GRAY);
        lblQuejas1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblQuejasMouseEntered

    private void lblQuejasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseExited
        // TODO add your handling code here:
        lblQuejas.setForeground(Color.BLACK);
        lblQuejas1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblQuejasMouseExited

    private void lblQuejas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejas1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuejas1MouseClicked

    private void lblQuejas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejas1MouseEntered
        // TODO add your handling code here:
        lblQuejas.setForeground(Color.GRAY);
        lblQuejas1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblQuejas1MouseEntered

    private void lblQuejas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejas1MouseExited
        // TODO add your handling code here:
        lblQuejas.setForeground(Color.BLACK);
        lblQuejas1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblQuejas1MouseExited

    private void lblTicketsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTicketsMouseEntered
        // TODO add your handling code here:
        lblTickets.setForeground(Color.GRAY);
        lblTickets1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblTicketsMouseEntered

    private void lblTicketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTicketsMouseExited
        // TODO add your handling code here:
        lblTickets.setForeground(Color.BLACK);
        lblTickets1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTicketsMouseExited

    private void lblSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin(); 
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSesionMouseClicked

    private void lblSesion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesion1MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin(); 
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSesion1MouseClicked

    private void lblSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseEntered
        // TODO add your handling code here:
        lblSesion.setForeground(Color.GRAY);
        lblSesion1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblSesionMouseEntered

    private void lblSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseExited
        // TODO add your handling code here:
        lblSesion.setForeground(Color.BLACK);
        lblSesion1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSesionMouseExited

    private void lblSesion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesion1MouseEntered
        // TODO add your handling code here:
        lblSesion.setForeground(Color.GRAY);
        lblSesion1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblSesion1MouseEntered

    private void lblSesion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesion1MouseExited
        // TODO add your handling code here:
        lblSesion.setForeground(Color.BLACK);
        lblSesion1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSesion1MouseExited

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblMantenimiento1;
    private javax.swing.JLabel lblQuejas;
    private javax.swing.JLabel lblQuejas1;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistrar1;
    private javax.swing.JLabel lblSesion;
    private javax.swing.JLabel lblSesion1;
    private javax.swing.JLabel lblTickets;
    private javax.swing.JLabel lblTickets1;
    private javax.swing.JPasswordField pwdConfirmarContrasenia;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
