package presentacion;

import java.awt.Color;
import javax.swing.BorderFactory;

public class FrmHome extends javax.swing.JFrame {

    private final ControlNavegacion control;
    
    /** Creates new form FrmAtnAlCliente */
    public FrmHome() {
        initComponents();
        
        this.control = new ControlNavegacion();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelMapa = new javax.swing.JLabel();
        jLabelQueja = new javax.swing.JLabel();
        jLabelAtnCliente = new javax.swing.JLabel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMapa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMapa.setText("Mapa");
        jLabelMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMapaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMapaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMapaMouseExited(evt);
            }
        });
        jPanel1.add(jLabelMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 90, 70));

        jLabelQueja.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelQueja.setText("Quejas");
        jLabelQueja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelQuejaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelQuejaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelQuejaMouseExited(evt);
            }
        });
        jPanel1.add(jLabelQueja, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 90, 70));

        jLabelAtnCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelAtnCliente.setText("Atención al cliente");
        jLabelAtnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtnClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAtnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAtnClienteMouseExited(evt);
            }
        });
        jPanel1.add(jLabelAtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 210, 90));

        jLabelCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCerrarSesion.setText("Cerrar sesión");
        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseExited(evt);
            }
        });
        jPanel1.add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 150, 90));

        jLabelInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelInicio.setText("Inicio");
        jLabelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInicioMouseExited(evt);
            }
        });
        jPanel1.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 90, 70));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 3 (7).png"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1120, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMouseClicked
        // TODO add your handling code here:
        jLabelInicio.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelInicioMouseClicked

    private void jLabelMapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMapaMouseClicked
        // TODO add your handling code here:
        control.cambiarPantalla(this, new FrmMapa());
    }//GEN-LAST:event_jLabelMapaMouseClicked

    private void jLabelQuejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuejaMouseClicked
        // TODO add your handling code here:
        control.cambiarPantalla(this, new FrmQuejas());
    }//GEN-LAST:event_jLabelQuejaMouseClicked

    private void jLabelAtnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtnClienteMouseClicked
        // TODO add your handling code here:
        control.cambiarPantalla(this, new FrmAtnAlCliente());
    }//GEN-LAST:event_jLabelAtnClienteMouseClicked

    private void jLabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseClicked
        // TODO add your handling code here:
        control.cambiarPantalla(this, new FrmLogin());
    }//GEN-LAST:event_jLabelCerrarSesionMouseClicked

    private void jLabelInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMouseEntered
        // TODO add your handling code here:
        jLabelInicio.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelInicioMouseEntered

    private void jLabelInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMouseExited
        // TODO add your handling code here:
        jLabelInicio.setForeground(Color.black);
    }//GEN-LAST:event_jLabelInicioMouseExited

    private void jLabelMapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMapaMouseEntered
        // TODO add your handling code here:
        jLabelMapa.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelMapaMouseEntered

    private void jLabelMapaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMapaMouseExited
        // TODO add your handling code here:
        jLabelMapa.setForeground(Color.black);
    }//GEN-LAST:event_jLabelMapaMouseExited

    private void jLabelQuejaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuejaMouseEntered
        // TODO add your handling code here:
        jLabelQueja.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelQuejaMouseEntered

    private void jLabelQuejaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuejaMouseExited
        // TODO add your handling code here:
        jLabelQueja.setForeground(Color.black);
    }//GEN-LAST:event_jLabelQuejaMouseExited

    private void jLabelAtnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtnClienteMouseEntered
        // TODO add your handling code here:
        jLabelAtnCliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelAtnClienteMouseEntered

    private void jLabelAtnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtnClienteMouseExited
        // TODO add your handling code here:
        jLabelAtnCliente.setForeground(Color.black);
    }//GEN-LAST:event_jLabelAtnClienteMouseExited

    private void jLabelCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseEntered
        // TODO add your handling code here:
        jLabelCerrarSesion.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelCerrarSesionMouseEntered

    private void jLabelCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseExited
        // TODO add your handling code here:
        jLabelCerrarSesion.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCerrarSesionMouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabelAtnCliente;
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelMapa;
    private javax.swing.JLabel jLabelQueja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
