package presentacion;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import ejteechiFacade.EjteechiFacade;
import ejteechiFacade.IEjteechiFacade;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Diego Valenzuela Parra - 00000247700
 * @author Juventino López García - 00000248547
 */
public class FrmLogin extends javax.swing.JFrame {
    private IEjteechiFacade ef;
    
    /** Creates new form Login */
    public FrmLogin(EjteechiFacade ef) {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            
        }
        
        initComponents();
        this.ef = ef;
        jLabel1.setBorder(BorderFactory.createMatteBorder(0,0,2,0, java.awt.Color.BLACK));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        lblCrearCuenta = new javax.swing.JLabel();
        pwdContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(224, 207, 163));

        jLabel1.setBorder(BorderFactory.createMatteBorder(0,0,3,0, java.awt.Color.BLACK));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ejteechi");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar sesión");

        txtCorreo.setBackground(new java.awt.Color(153, 149, 149));
        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setText("Correo");
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(34, 34, 34));
        btnIniciar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(224, 207, 163));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblCrearCuenta.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
        lblCrearCuenta.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblCrearCuenta.setText("Aún no tengo cuenta");
        lblCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseExited(evt);
            }
        });

        pwdContra.setBackground(new java.awt.Color(153, 149, 149));
        pwdContra.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        pwdContra.setForeground(new java.awt.Color(0, 0, 0));
        pwdContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwdContra.setText("********");
        pwdContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdContraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdContraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCrearCuenta)
                    .addComponent(btnIniciar)
                    .addComponent(pwdContra, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(pwdContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnIniciar)
                .addGap(42, 42, 42)
                .addComponent(lblCrearCuenta)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseClicked
        ef.cambiarPantalla(this, new FrmRegistrar(new EjteechiFacade()));
    }//GEN-LAST:event_lblCrearCuentaMouseClicked

    private void lblCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseEntered
        lblCrearCuenta.setForeground(Color.WHITE);
        lblCrearCuenta.setBorder(BorderFactory.createMatteBorder(0,0,2,0, java.awt.Color.WHITE));
    }//GEN-LAST:event_lblCrearCuentaMouseEntered

    private void lblCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseExited
        lblCrearCuenta.setForeground(Color.BLACK);
        lblCrearCuenta.setBorder(BorderFactory.createMatteBorder(0,0,2,0, java.awt.Color.BLACK));
    }//GEN-LAST:event_lblCrearCuentaMouseExited

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if (txtCorreo.getText().equals("Correo")) {
            txtCorreo.setText("");
        }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if (txtCorreo.getText().equals("")) {
            txtCorreo.setText("Correo");
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void pwdContraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraFocusGained
        if (String.valueOf(pwdContra.getPassword()).equals("********")) {
            pwdContra.setText("");
        }
    }//GEN-LAST:event_pwdContraFocusGained

    private void pwdContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraFocusLost
        if (String.valueOf(pwdContra.getPassword()).equals("")) {
            pwdContra.setText("********");
        }
    }//GEN-LAST:event_pwdContraFocusLost

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        ef.cambiarPantalla(this, new FrmHome(new EjteechiFacade()));
    }//GEN-LAST:event_btnIniciarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPasswordField pwdContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

}
