package presentacion;

import java.awt.Color;
import javax.swing.BorderFactory;

public class FrmLogin extends javax.swing.JFrame {
    
    private final ControlNavegacion control;
    
    /** Creates new form Login */
    public FrmLogin() {
        initComponents();
                        
        this.control = new ControlNavegacion();
        
        jLabel1.setBorder(BorderFactory.createMatteBorder(0,0,2,0, java.awt.Color.BLACK));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        lblCrearCuenta = new javax.swing.JLabel();
        pwdContra = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(178, 178, 178));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(BorderFactory.createMatteBorder(0,0,3,0, java.awt.Color.BLACK));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 100)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 37, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(153, 149, 149));
        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlPrincipal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 290, -1));

        btnIniciar.setBackground(new java.awt.Color(34, 34, 34));
        btnIniciar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(224, 207, 163));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, -1, -1));

        lblCrearCuenta.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
        lblCrearCuenta.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblCrearCuenta.setText("Aún no tengo cuenta");
        lblCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseExited(evt);
            }
        });
        pnlPrincipal.add(lblCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, -1, -1));

        pwdContra.setBackground(new java.awt.Color(153, 149, 149));
        pwdContra.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        pwdContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlPrincipal.add(pwdContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 290, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/slogan3.0.png"))); // NOI18N
        pnlPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo2Ejteechi.png"))); // NOI18N
        pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contraseñaEjteechi.png"))); // NOI18N
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, 40));

        jLabel1.setBorder(BorderFactory.createMatteBorder(0,0,3,0, java.awt.Color.BLACK));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 100)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoEjteechi.png"))); // NOI18N
        pnlPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 27, 530, 240));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicioSesionEjeteechi.png"))); // NOI18N
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 430, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/divisionLogin (1).png"))); // NOI18N
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, -1, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseClicked
        control.cambiarPantalla(this, new FrmRegistrar());
    }//GEN-LAST:event_lblCrearCuentaMouseClicked

    private void lblCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseEntered
        lblCrearCuenta.setForeground(Color.WHITE);
        lblCrearCuenta.setBorder(BorderFactory.createMatteBorder(0,0,2,0, java.awt.Color.WHITE));
    }//GEN-LAST:event_lblCrearCuentaMouseEntered

    private void lblCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseExited
        lblCrearCuenta.setForeground(Color.BLACK);
        lblCrearCuenta.setBorder(BorderFactory.createMatteBorder(0,0,2,0, java.awt.Color.BLACK));
    }//GEN-LAST:event_lblCrearCuentaMouseExited

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        control.cambiarPantalla(this, new FrmHome());
    }//GEN-LAST:event_btnIniciarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPasswordField pwdContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

}
